import React from 'react';
import { View, Text, StyleSheet, ScrollView, Image } from 'react-native';
import QRCode from 'react-native-qrcode-svg';
const TransactionDetails = ({ route }) => {
    const { purchase } = route.params;


    const getMonthName = (monthNumber) => {
        const months = [
            'January', 'February', 'March', 'April', 'May', 'June',
            'July', 'August', 'September', 'October', 'November', 'December'
        ];
        return months[parseInt(monthNumber) - 1];
    };


    const formatDate = (date) => {
        const [month, day, year] = date.split('/');
        const monthName = getMonthName(month);
        return `${monthName} ${day}, ${year}`;
    };

    return (
        <ScrollView style={styles.container}>
            {/* Logo at the top-center */}
            <View style={styles.logoContainer}>
                <Image
                    source={require('../../../pics/mainlogo.png')}
                    style={styles.logo}
                />
            </View>

            {/* Date and Time at the top */}
            <View style={styles.dateTimeContainer}>
                <Text style={styles.detailsText}>
                    <Text style={styles.boldText}>Date:</Text> {formatDate(purchase.date)}
                </Text>
                <Text style={styles.detailsText}>
                    <Text style={styles.boldText}>Time:</Text> {purchase.time}
                </Text>
            </View>

            {/* Product Table */}
            <View style={styles.tableContainer}>
                <View style={styles.tableHeader}>
                    <Text style={[styles.tableText, styles.boldText]}>Product</Text>
                    <Text style={[styles.tableText, styles.boldText]}>Quantity</Text>
                    <Text style={[styles.tableText, styles.boldText]}>Price</Text>
                </View>

                {purchase.cart && purchase.cart.map((product, index) => (
                    <View key={index} style={styles.tableRow}>
                        <Text style={styles.tableText}>{product.productName}</Text>
                        <Text style={styles.tableText}>{product.quantity}</Text>
                        <Text style={styles.tableText}>Rs. {product.price}/-</Text>
                    </View>
                ))}
            </View>

            <View style={styles.totalBillContainer}>
                <Text style={[styles.detailsText]}>
                    <Text style={styles.boldText}>Total Bill: </Text>
                    <Text style={styles.normalText}> Rs. {purchase.totalBill}/-</Text>
                </Text>
            </View>
            <View style={styles.notesContainer}>
                <Text style={styles.noteText}></Text>
                <Text style={styles.noteText}>Bring Invoice for return/exchange within 5 days of purchase.{'\n'}
                    No return or Exchange on{'\n'}Crockery, Toys, Cosmetics & Frozen Items{'\n'}</Text>
                <View style={styles.qrCodeContainer}>
                    <QRCode
                        value="This receipt is originally generated by &copy; Shopnpay 2024"  // You can customize this value as needed
                        size={100}
                        color="black"
                        backgroundColor="white"
                        style={styles.qrCode}
                    />
                </View>
                <Text style={styles.signatureText}>This receipt is computer-generated and digitally signed. No need of any signatures</Text>
                <Text style={styles.noteText}><Text style={styles.boldText2}>Developed by &copy; <Text style={styles.colorful}><Text style={styles.boldText2}>Shopnpay</Text></Text> 2024</Text> </Text>
            </View>
        </ScrollView>
    );
};

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        padding: 20,
    },
    logoContainer: {
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
    },
    logo: {
        width: 200,
        height: 70,
        resizeMode: 'contain',
    },
    dateTimeContainer: {
        marginBottom: 20,
    },
    detailsText: {
        fontSize: 16,
        marginBottom: 8,
    },
    boldText: {
        fontWeight: 'bold',
        fontSize: 16,
        color: '#A52A2A',
    },
    normalText: {
        fontSize: 14,
    },
    tableContainer: {
        marginBottom: 10,
        borderTopWidth: 0.5,
        borderTopColor: 'black',
        borderBottomWidth: 0.5,
        borderBottomColor: 'black',
    },
    tableHeader: {
        flexDirection: 'row',
        fontSize: 16,
        justifyContent: 'space-between',
        borderBottomWidth: 0.5,
        borderBottomColor: 'black',
        paddingVertical: 8,
    },
    tableRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: 8,
    },
    tableText: {
        fontSize: 12,
        width: '30%',
        textAlign: 'center',
    },
    totalBillContainer: {
        marginTop: 20,
        alignItems: 'flex-end',
    },
    notesContainer: {
        marginTop: 10,
        paddingTop: 10,
    },
    noteText: {
        fontSize: 13,
        textAlign: 'center',
        color: 'grey',
        fontFamily: 'Raleway-Regular',
    },
    signatureText: {
        fontSize: 12,
        textAlign: 'center',
        marginTop: 30,
        fontStyle: 'italic',
        color: 'grey',
        marginBottom: 10,
    },
    qrCodeContainer: {
        alignItems: 'center',
        marginTop: 20,
    },
    qrCodeText: {
        fontSize: 14,
        marginBottom: 5,
        color: 'black',
        fontFamily: 'Raleway-Regular',
    },
    qrCode: {
        marginTop: 10,
    },
    colorful: {
        color: '#A52A2A',
    },
    boldText2: {
        fontWeight: 'bold',
        fontFamily: 'Raleway-Regular',
    },
});

export default TransactionDetails;
